title: Ada Antolak's Portfolio
description: >-
  Ada Antolak's portfolio.

markdown: kramdown
plugins:

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml

collections:
  images:
    output: true
    permalink: /:path
