version: "3"

services:
  web:
    build: .
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/app
      - bundle:/bundle
    command: bundle exec jekyll serve -H 0.0.0.0 --livereload

volumes:
  bundle:
